name: latex-compile

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Run paperaj to process document environment
      - name: Run paperaj
        uses: dermatologist/paperaj@master
        with:
          env-file: paperaj.env

      # Compile the LaTeX document
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: clean
          root_file: main.tex

      # Upload the compiled PDF as an artifact
      - name: Upload LaTeX PDF
        uses: actions/upload-artifact@v4
        with:
          name: article
          path: clean/main.pdf
          retention-days: 5
